// This file is automatically generated. Do not modify it manually.
// For more information, see the Firebase CLI documentation:
// https://firebase.google.com/docs/cli

import { initializeApp, getApp, getApps } from 'firebase/app';

const firebaseConfig = {"apiKey":"AIzaSyDiSS4Mms4tOFNTTbr2KEi1J49tC_912fU","authDomain":"fair-future-477412-e5.firebaseapp.com","projectId":"fair-future-477412-e5","storageBucket":"fair-future-477412-e5.appspot.com","messagingSenderId":"492348575003","appId":"1:492348575003:web:011a0d33e54b6d4b4a1b02","measurementId":"G-1521TSE93Z"};

function initializeFirebase() {
  if (getApps().length > 0) {
    return getApp();
  }
  return initializeApp(firebaseConfig);
}

export const firebaseApp = initializeFirebase();
