// This file is automatically generated. Do not modify it manually.
// For more information, see the Firebase CLI documentation:
// https://firebase.google.com/docs/cli

import { initializeApp, getApp, getApps } from 'firebase/app';

const firebaseConfig = {"apiKey":"AIzaSyCbkTh5KHwrar-OT9lVUT4s94DJzP_7F7M","authDomain":"fair-future-477412-e5.firebaseapp.com","projectId":"fair-future-477412-e5","storageBucket":"fair-future-477412-e5.appspot.com","messagingSenderId":"949447084445","appId":"1:949447084445:web:2fe8ec1d77af1b50e60774","measurementId":""};

function initializeFirebase() {
  if (getApps().length > 0) {
    return getApp();
  }
  return initializeApp(firebaseConfig);
}

export const firebaseApp = initializeFirebase();
